name: Deploy Multiple AWS Lambda Functions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda: [generate_key, resolve_key]  # List your Lambda function names here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify Python version 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if any

      - name: Create ZIP package
        run: cd src && zip -r ../${{ matrix.lambda }}.zip ${{ matrix.lambda }}.py

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ${{ matrix.lambda }} --zip-file fileb://${{ matrix.lambda }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
