name: Deploy Multiple AWS Lambda Functions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 2  # Fetch the previous commit to check for changes
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify Python version 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if any

      - name: Check for changes in Lambda function directory
        id: check_changes
        run: |
          changed_files=$(git diff --name-only main origin/main | grep '^src/' | tr '\n' ',')
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Deploy Lambda Function with .zip Deployment Package
        id: deploy_lambda
        if: steps.check_changes.outputs.changed_files != ''
        run: |
          changed_files="${{ steps.check_changes.outputs.changed_files }}"
          IFS=',' read -r -a files <<< "$changed_files"
          for file in "${files[@]}"; do
            echo "Deploying $file ..."

            file_with_extension="${file##*/}"
            file_without_extension="${file_with_extension%.py}"

            cd ./src/
            echo "Creating zip file: ${file_without_extension}.zip"
            zip -r "../${file_without_extension}.zip" "$file_with_extension"

            echo "Deploying updated Lambda function: ${file_without_extension} ..."
            aws lambda update-function-code --function-name "${file_without_extension}" --zip-file fileb://"../${file_without_extension}.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
