name: Deploy Multiple AWS Lambda Functions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lambda: [generate_key, resolve_key]  # List your Lambda function names here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify Python version 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if any

      - name: Check for changes in Lambda function directory
        id: check_changes
        run: |
          echo "Checking for changes in /src directory..."
          if git diff --name-only HEAD~1 HEAD | grep '^src/'; then
            echo "src-changes=true" >> $GITHUB_ENV
          else
            echo "src-changes=false" >> $GITHUB_ENV
          fi

      - name: Deploy Lambda Function with .zip Deployment Package
        if: env.src-changes == 'true'
        run: |
          echo "Deploying updated Lambda functions..."
          # Package your Lambda function
          cd src  # Navigate to the src directory again if needed
          zip -r ../${{ matrix.lambda }}.zip ${{ matrix.lambda }}.py
          
          aws lambda update-function-code --function-name ${{ matrix.lambda }} --zip-file fileb://${{ matrix.lambda }}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
